from __future__ import annotations
import json
import urllib.request
import urllib.error
from typing import Optional


METHODS_TEMPLATE = """
{test_name} was used to {comparison_description}. 
The test was selected because {rationale}. 
{results_summary}
Effect size ({effect_type} = {effect_size:.3f}) indicated a 
{effect_magnitude} practical effect.
"""

OLLAMA_PROMPT = """You are a scientific writing assistant. 
Convert this statistical result into ONE publication-ready methods sentence.
Be precise, concise, and use APA 7th edition format.

Test: {test_name}
Statistic: {statistic:.3f}
p-value: {p_value:.4f}
Effect size: {effect_type} = {effect_size:.3f}
Rationale: {rationale}
N groups/conditions: {n_groups}

Output: ONE sentence only, no preamble, no explanation.
"""


def _ollama_available(base_url: str = "http://localhost:11434") -> bool:
    try:
        req = urllib.request.Request(f"{base_url}/api/tags")
        with urllib.request.urlopen(req, timeout=3) as r:
            return r.status < 400
    except Exception:
        return False


def _call_ollama(
    prompt: str,
    model: str = "qwen2.5",
    base_url: str = "http://localhost:11434"
) -> Optional[str]:
    payload = json.dumps({
        "model": model,
        "prompt": prompt,
        "stream": False,
        "options": {"temperature": 0}
    }).encode('utf-8')
    
    req = urllib.request.Request(
        f"{base_url}/api/generate",
        data=payload,
        headers={"Content-Type": "application/json"},
        method="POST"
    )
    
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            result = json.loads(r.read().decode('utf-8'))
            return str(result.get('response', '')).strip()
    except Exception:
        return None


def generate_methods_paragraph(
    test_result: dict,
    profile: dict,
    use_llm: bool = True,
    model: str = "qwen2.5"
) -> str:

    test_name = test_result.get('test', 'Unknown test')
    statistic = test_result.get('statistic', 0.0)
    p_value = test_result.get('p_value', 1.0)
    effect_size = test_result.get('effect_size', 0.0)
    effect_type = test_result.get('effect_type', 'effect size')
    
    rec = profile.get('recommendation', {})
    rationale = rec.get('rationale', '')
    n_groups = profile.get('n_groups', 2)
    
    # Effect magnitude interpretation
    if effect_type == 'cohen_d':
        thresholds = [(0.8, 'large'), (0.5, 'medium'), (0.2, 'small')]
    elif effect_type in ('eta_squared', 'epsilon_squared'):
        thresholds = [(0.14, 'large'), (0.06, 'medium'), (0.01, 'small')]
    elif effect_type == 'kendalls_w':
        thresholds = [(0.5, 'large'), (0.3, 'medium'), (0.1, 'small')]
    else:
        thresholds = [(0.5, 'large'), (0.3, 'medium'), (0.1, 'small')]
    
    effect_magnitude = 'negligible'
    for threshold, label in thresholds:
        if abs(effect_size) >= threshold:
            effect_magnitude = label
            break
    
    p_str = "< 0.001" if p_value < 0.001 else f"= {p_value:.3f}"
    
    # Try LLM first
    if use_llm and _ollama_available():
        prompt = OLLAMA_PROMPT.format(
            test_name=test_name,
            statistic=statistic,
            p_value=p_value,
            effect_type=effect_type,
            effect_size=effect_size,
            rationale=rationale,
            n_groups=n_groups
        )
        llm_output = _call_ollama(prompt, model=model)
        
        if llm_output and len(llm_output) > 20:
            return f"{llm_output}\n[Generated by {model} via Ollama]"
    
    # Template fallback — always works
    test_display = test_name.replace('_', ' ').title()
    significance = f"p {p_str}"
    
    if p_value < 0.05:
        conclusion = "a statistically significant effect was detected"
    else:
        conclusion = "no statistically significant effect was detected"
    
    return (
        f"A {test_display} was conducted to compare groups ({rationale.lower()}). "
        f"Results indicated {conclusion} "
        f"(statistic = {statistic:.3f}, {significance}, "
        f"{effect_type} = {effect_size:.3f}, {effect_magnitude} effect)."
        f"\n[Generated by template fallback — install Ollama for enhanced output]"
    )